### ISSUE TITLE
creates empty pack

### ISSUE THREAD

**Issue by bnjmn21** [GDColon/GD-Randomizer#1]
Creates empy pack in v1.0!
In v1.1 leaves the following error.

PC Specs:
Windows 8.1 64-bit
Intel Core i5-3337U at 1.80Ghz both cores, 64-bit
8,00GB RAM
[crash_log.txt](https://github.com/GDColon/GD-Randomizer/files/4914994/crash_log.txt)

**Comment by GDColon** [comment]
Seems to be an issue with the .plist file - does this still happen in verison 1.2?

**Comment by bnjmn21** [comment]
I think its working now!
