### ISSUE TITLE
Doesn't shuffle

### ISSUE THREAD

**Issue by mario64thane** [GDColon/GD-Randomizer#13]
It makes the pack folder but it doesn't shuffle anything, and when I apply it, it does nothing.
Here's the pack it made:
[pack.zip](https://github.com/GDColon/GD-Randomizer/files/5892138/pack.zip)

**Comment by GDColon** [comment]
It seems like the textures shuffled just fine. Make sure you're on UHD graphics and make sure you put the files into GD's resources folder
