### ISSUE TITLE
where mac

### ISSUE THREAD

**Issue by ghost** [GDColon/GD-Randomizer#16]
please # #15

**Comment by Just-a-Unity-Dev** [comment]
you can easily downlaod the src, get node.js and run it locally

**Comment by Rudxain** [comment]
I'll probably fork the repo to add Mac and Android support.

The procedure for Android should probably be the same but it would require running NodeJS on Termux, using `pm path com.robtopx.geometryjump` to get the install diretory, copy the APK while renaming the extension to .zip, unzip, apply the usual procedure on whatever name the resources folder has there, zip again, rename .zip to .apk, and ask the user to apply the "update" (Android updates apps when you try to reinstall them). If the user has root, the script can install without asking

**Comment by Rudxain** [comment]
I gave up, I can only add support for MacOS & Windows. I could do it for Android but it requires a different algorithm
