### ISSUE TITLE
compile that boi

### ISSUE THREAD

**Issue by the-one-with-raspberry** [GDColon/GD-Randomizer#17]
It game me a compilation error: 
![err](https://user-images.githubusercontent.com/72183318/130027650-cd099ef3-8b37-4dc0-a889-f787036b6d2c.jpg)

**Comment by unkn0wncvm1** [comment]
`<marquee did you use node js</marquee>`

**Comment by Just-a-Unity-Dev** [comment]
you're using JScript and not Javascript. did you download the source or a release?

**Comment by the-one-with-raspberry** [comment]
> you're using JScript and not Javascript. did you download the source or a release?

How should I?

**Comment by Just-a-Unity-Dev** [comment]
well... download it on google?

**Comment by Just-a-Unity-Dev** [comment]
[here's the download link](https://nodejs.org/), install it, then launch a terminal (cmd) in the source directory. then do

```
node shuffle.js
```

BE SURE TO BACKUP YOUR FILES

**Comment by the-one-with-raspberry** [comment]
> [here's the download link](https://nodejs.org/), install it, then launch a terminal (cmd) in the source directory. then do
> 
> ```
> node shuffle.js
> ```
> 
> BE SURE TO BACKUP YOUR FILES

ok
