### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by yeaa132** [GDColon/GD-Randomizer#19]
Crashes the game when I put the pack in

**Comment by Rudxain** [comment]
That's weird. Maybe it's because of an edge case when swapping textures? What exactly did you do? (steps to reproduce the bug). Did you made a backup? If not, you need to download the Resources folder from someone with a copy of GD, or use Steam's corruption fix, or just reinstall GD completely

**Comment by yeaa132** [comment]
Wait, I know why. I renamed the folder that had the generated textures to "Resources". And then I slapped it in the GD folder, ran it, and crashed! The problem was that there were no information files (.json .txt etc) Then I tried copying the backup resources (on my Desktop) and pasting them into the GD folder, and then ran the randomizer's exe then copied everything in the folder, then pasted it all in the Resources folder, then overwriting it, then running GD, and it worked.

**Comment by Rudxain** [comment]
I didn't understand but good for you, lol. You solved the problem
