### ISSUE TITLE
Small issue

### ISSUE THREAD

**Issue by Appletwo985** [GDColon/GD-Randomizer#7]
Whenever I run shuffle.exe, it does create a "pack" folder, but it's not what it's supposed to be. It only creates some of the files and they're all not even shuffled. I mean that they're all normal. I tried that multiple times. Here's the zipped pack folder that it keeps creating instead of normally shuffling the textures:
[pack.zip](https://github.com/GDColon/GD-Randomizer/files/5024279/pack.zip)
Also, sorry for bad english

**Comment by GDColon** [comment]
It's working exactly as intended. Not all files are shuffled. Just overwrite the old GD files with the ones made from the program
